services:
  mongodb:
    container_name: mongodb
    image: mongo:6.0
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: iso
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    command: mongod --logpath /var/log/mongodb/mongod.log --logappend
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh mongodb://root:root@localhost:27017/admin --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

  mongo-express:
    container_name: mongo-express
    image: mongo-express:1.0.0-alpha.4
    restart: unless-stopped
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongodb:27017/
      ME_CONFIG_MONGODB_AUTH_DATABASE: admin
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: root
    ports:
      - "8081:8081"

volumes:
  mongodb_data: